# Site settings
title: KEO Studio Photography in Melbourne - by Svetlana Pelin
description: Commercial photographer in Melbourne
baseurl: "/"

# Build settings
markdown: kramdown

highlighter: rouge

plugins:
  - jekyll-sitemap

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

settings:
  logo: /media/logo.png
